<?php
require_once '../includes/db.php';
require_once '../includes/functions.php';
redirectToLogin();

$pageTitle = 'HA Settings';
$message = null;

// Helper: get setting from DB
function getSetting($pdo, $key, $default = '') {
    try {
        $stmt = $pdo->prepare("SELECT setting_value FROM ha_settings WHERE setting_key = ?");
        $stmt->execute([$key]);
        $row = $stmt->fetch();
        return $row ? $row['setting_value'] : $default;
    } catch(Exception $e) { return $default; }
}

// Helper: save setting
function saveSetting($pdo, $key, $value) {
    $stmt = $pdo->prepare("INSERT INTO ha_settings (setting_key, setting_value) VALUES (?, ?)
                            ON DUPLICATE KEY UPDATE setting_value = ?");
    $stmt->execute([$key, $value, $value]);
}

// Handle save
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['save_ha'])) {
    $fields = ['ha_url', 'ha_token', 'ha_enabled', 'site_a_name', 'site_b_name'];
    foreach ($fields as $field) {
        $val = isset($_POST[$field]) ? trim($_POST[$field]) : '';
        saveSetting($pdo, $field, $val);
    }
    saveSetting($pdo, 'pump_meters_enabled', isset($_POST['pump_meters_enabled']) ? '1' : '0');
    // Also update the iot_config.php file with new values so ha_proxy works immediately
    $ha_url   = sanitize($_POST['ha_url']);
    $ha_token = trim($_POST['ha_token']);
    $config = "<?php\n/**\n * Home Assistant Credentials — Auto-generated by Admin Panel\n * DO NOT UPLOAD TO GITHUB\n */\n\ndefine('HA_URL', '" . addslashes($ha_url) . "');\ndefine('HA_TOKEN', '" . addslashes($ha_token) . "');\n?>";
    file_put_contents('../includes/iot_config.php', $config);
    $message = ['type' => 'success', 'text' => 'HA Settings saved and config file updated!'];
}

// Handle pattern save (separate form)
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['save_pattern'])) {
    $newPattern = trim($_POST['control_pattern'] ?? '');
    if (strlen($newPattern) >= 4 && preg_match('/^[1-9]+$/', $newPattern)) {
        $hashed = password_hash($newPattern, PASSWORD_BCRYPT);
        saveSetting($pdo, 'control_pattern', $hashed);
        $message = ['type' => 'success', 'text' => 'Control pattern updated successfully!'];
    } else {
        $message = ['type' => 'error', 'text' => 'Pattern must be at least 4 digits (1–9 only).'];
    }
}

$patternIsSet = (getSetting($pdo, 'control_pattern', '') !== '');

// Load current settings
$ha_url      = getSetting($pdo, 'ha_url', 'https://');
$ha_token    = getSetting($pdo, 'ha_token', '');
$ha_enabled  = getSetting($pdo, 'ha_enabled', '1');
$site_a_name = getSetting($pdo, 'site_a_name', 'Shop');
$site_b_name = getSetting($pdo, 'site_b_name', 'Home');
$pump_meters_enabled = getSetting($pdo, 'pump_meters_enabled', '0');
?>
<?php include 'includes/admin_head.php'; ?>
<?php include 'includes/sidebar.php'; ?>

    <?php if ($message): ?>
    <div class="mb-6 px-4 py-3 rounded-xl text-sm font-medium flex items-center gap-3
        <?php echo $message['type'] === 'success' ? 'bg-green-500/10 text-green-400 border border-green-500/20' : 'bg-red-500/10 text-red-400 border border-red-500/20'; ?>">
        <i class="fa-solid <?php echo $message['type'] === 'success' ? 'fa-circle-check' : 'fa-circle-xmark'; ?>"></i>
        <?php echo $message['text']; ?>
    </div>
    <?php endif; ?>

    <div class="grid grid-cols-1 lg:grid-cols-3 gap-6">

        <!-- Settings Form -->
        <div class="lg:col-span-2 space-y-6">

            <!-- Connection Settings -->
            <div class="glass-card rounded-2xl border border-gray-800 overflow-hidden">
                <div class="px-6 py-4 border-b border-gray-800 flex items-center justify-between">
                    <div class="flex items-center gap-3">
                        <div class="w-8 h-8 rounded-lg bg-blue-500/15 flex items-center justify-center">
                            <i class="fa-solid fa-plug text-blue-400 text-sm"></i>
                        </div>
                        <h2 class="font-bold text-white">Connection Settings</h2>
                    </div>
                    <span id="test-badge" class="hidden px-3 py-1 rounded-full text-xs font-bold"></span>
                </div>
                <div class="p-6">
                    <form method="POST" class="space-y-5">
                        <input type="hidden" name="save_ha" value="1">

                        <div class="flex items-center justify-between p-4 bg-gray-800/50 rounded-xl border border-gray-700">
                            <div>
                                <p class="text-sm font-bold text-white">Enable Home Assistant</p>
                                <p class="text-xs text-gray-500 mt-0.5">Disable to show offline state everywhere</p>
                            </div>
                            <label class="toggle-switch">
                                <input type="checkbox" name="ha_enabled" value="1" <?php echo $ha_enabled ? 'checked' : ''; ?>>
                                <span class="toggle-slider"></span>
                            </label>
                        </div>

                        <div class="flex items-center justify-between p-4 bg-gray-800/50 rounded-xl border border-gray-700">
                            <div>
                                <p class="text-sm font-bold text-white">Show Pump Meters/Gauges</p>
                                <p class="text-xs text-gray-500 mt-0.5">hacontrol.php Shop Pump card: show voltage/amps gauges + power/kWh/freq stats. Off = just the START/STOP switch.</p>
                            </div>
                            <label class="toggle-switch">
                                <input type="checkbox" name="pump_meters_enabled" value="1" <?php echo $pump_meters_enabled === '1' ? 'checked' : ''; ?>>
                                <span class="toggle-slider"></span>
                            </label>
                        </div>

                        <div>
                            <label class="block text-xs text-gray-500 uppercase font-bold mb-1.5">Home Assistant URL</label>
                            <div class="flex gap-2">
                                <input type="url" name="ha_url" id="ha_url" value="<?php echo htmlspecialchars($ha_url); ?>" required
                                    class="flex-1 px-3 py-2.5 bg-gray-800 border border-gray-700 rounded-xl text-white text-sm placeholder-gray-600"
                                    placeholder="https://your-ha.duckdns.org">
                                <button type="button" onclick="testConnection()"
                                    class="px-4 py-2.5 bg-gray-700 hover:bg-gray-600 text-gray-300 rounded-xl text-sm font-medium transition whitespace-nowrap">
                                    <i class="fa-solid fa-plug mr-1"></i> Test
                                </button>
                            </div>
                            <p class="text-[10px] text-gray-600 mt-1">Example: https://power.mtpretails.in or http://192.168.1.x:8123</p>
                        </div>

                        <div>
                            <label class="block text-xs text-gray-500 uppercase font-bold mb-1.5">Long-Lived Access Token (LAT)</label>
                            <div class="relative">
                                <input type="password" name="ha_token" id="ha_token" value="<?php echo htmlspecialchars($ha_token); ?>"
                                    class="w-full px-3 py-2.5 bg-gray-800 border border-gray-700 rounded-xl text-white text-sm font-mono pr-12"
                                    placeholder="eyJhbGciOiJ...">
                                <button type="button" onclick="toggleToken()"
                                    class="absolute right-3 top-1/2 -translate-y-1/2 text-gray-500 hover:text-gray-300 transition">
                                    <i class="fa-solid fa-eye text-sm" id="token-eye"></i>
                                </button>
                            </div>
                            <p class="text-[10px] text-gray-600 mt-1">
                                Get this from HA → Profile → Long-Lived Access Tokens → Create token
                            </p>
                        </div>

                        <div class="grid grid-cols-2 gap-4">
                            <div>
                                <label class="block text-xs text-gray-500 uppercase font-bold mb-1.5">Site A Name</label>
                                <input type="text" name="site_a_name" value="<?php echo htmlspecialchars($site_a_name); ?>"
                                    class="w-full px-3 py-2.5 bg-gray-800 border border-gray-700 rounded-xl text-white text-sm"
                                    placeholder="Shop">
                                <p class="text-[10px] text-gray-600 mt-1">Label for the first power site</p>
                            </div>
                            <div>
                                <label class="block text-xs text-gray-500 uppercase font-bold mb-1.5">Site B Name</label>
                                <input type="text" name="site_b_name" value="<?php echo htmlspecialchars($site_b_name); ?>"
                                    class="w-full px-3 py-2.5 bg-gray-800 border border-gray-700 rounded-xl text-white text-sm"
                                    placeholder="Home">
                                <p class="text-[10px] text-gray-600 mt-1">Label for the second power site</p>
                            </div>
                        </div>

                        <div class="flex gap-3 pt-2">
                            <button type="submit"
                                class="px-6 py-2.5 bg-blue-600 hover:bg-blue-500 text-white font-bold rounded-xl transition text-sm flex items-center gap-2">
                                <i class="fa-solid fa-save"></i> Save Settings
                            </button>
                            <button type="button" onclick="testConnection()"
                                class="px-6 py-2.5 bg-gray-700 hover:bg-gray-600 text-white font-bold rounded-xl transition text-sm flex items-center gap-2">
                                <i class="fa-solid fa-wifi"></i> Test Connection
                            </button>
                        </div>
                    </form>
                </div>
            </div>

            <!-- Control Pattern (hacontrol.php) -->
            <div class="glass-card rounded-2xl border border-gray-800 overflow-hidden">
                <div class="px-6 py-4 border-b border-gray-800 flex items-center gap-3">
                    <div class="w-8 h-8 rounded-lg bg-purple-500/15 flex items-center justify-center">
                        <i class="fa-solid fa-lock text-purple-400 text-sm"></i>
                    </div>
                    <div>
                        <h2 class="font-bold text-white">HA Control Pattern Lock</h2>
                        <p class="text-xs text-gray-500">Pattern used to authorize switch control on public hacontrol.php</p>
                    </div>
                    <span class="ml-auto px-2.5 py-1 rounded-full text-xs font-bold
                        <?php echo $patternIsSet ? 'bg-green-500/10 text-green-400 border border-green-500/20' : 'bg-yellow-500/10 text-yellow-400 border border-yellow-500/20'; ?>">
                        <?php echo $patternIsSet ? '✓ Pattern Set' : '! Using Default'; ?>
                    </span>
                </div>
                <div class="p-6">
                    <form method="POST" class="space-y-5" id="pattern-form">
                        <input type="hidden" name="save_pattern" value="1">

                        <div>
                            <label class="block text-xs text-gray-500 uppercase font-bold mb-1.5">Draw New Pattern</label>
                            <div class="flex flex-col items-center gap-3">
                                <!-- Live sequence display -->
                                <div class="w-full flex items-center justify-between px-1">
                                    <span class="text-[10px] text-gray-600 uppercase font-bold">Dot layout: 1 2 3 / 4 5 6 / 7 8 9</span>
                                    <span class="text-[10px] text-gray-500">min 4 dots</span>
                                </div>
                                <!-- Canvas -->
                                <canvas id="pattern-canvas"
                                    class="rounded-2xl border border-gray-700 bg-gray-800/80 cursor-pointer block"
                                    style="touch-action:none; width:200px; height:200px;"></canvas>
                                <!-- Live sequence readout -->
                                <div id="pattern-live" class="text-center">
                                    <p class="text-[10px] text-gray-600 mb-1">Sequence recorded:</p>
                                    <p id="pattern-seq-display" class="text-2xl font-black text-white tracking-[0.3em] font-mono min-h-[2rem]">—</p>
                                </div>
                                <!-- Hidden input for form submit -->
                                <input type="hidden" name="control_pattern" id="pattern-input">
                                <div class="flex gap-2 w-full">
                                    <button type="button" onclick="adminPatternClear()"
                                        class="flex-1 py-2 bg-gray-700 hover:bg-gray-600 text-gray-400 rounded-xl text-sm transition flex items-center justify-center gap-2">
                                        <i class="fa-solid fa-rotate-left"></i> Clear
                                    </button>
                                </div>
                                <p class="text-[10px] text-gray-600">Note the sequence above — you must draw the <strong>exact same sequence</strong> on hacontrol.php</p>
                            </div>
                        </div>

                        <div class="p-3 bg-yellow-500/5 border border-yellow-500/15 rounded-xl text-xs text-yellow-500/80 flex gap-2">
                            <i class="fa-solid fa-triangle-exclamation mt-0.5 flex-shrink-0"></i>
                            <div>
                                Default pattern is <strong>1-2-3-5</strong> (top row left→right, then center).
                                Dot layout: <span class="font-mono text-gray-400">1 2 3 / 4 5 6 / 7 8 9</span>
                                (top-left=1, bottom-right=9). Stored as bcrypt hash — cannot be recovered, only reset.
                            </div>
                        </div>

                        <button type="submit"
                            class="px-6 py-2.5 bg-purple-600 hover:bg-purple-500 text-white font-bold rounded-xl transition text-sm flex items-center gap-2">
                            <i class="fa-solid fa-lock"></i> Update Pattern
                        </button>
                    </form>
                </div>
            </div>

        </div>

        <!-- Info / Help Sidebar -->
        <div class="space-y-4">

            <!-- Connection Status Live -->
            <div class="glass-card rounded-2xl border border-gray-800 p-5">
                <h3 class="font-bold text-white mb-4 flex items-center gap-2">
                    <i class="fa-solid fa-satellite-dish text-blue-400"></i> Live Status
                </h3>
                <div id="status-result" class="space-y-3 text-sm">
                    <div class="flex items-center gap-3 p-3 bg-gray-800/50 rounded-xl">
                        <div class="w-2 h-2 rounded-full bg-gray-500 animate-pulse" id="status-dot"></div>
                        <span class="text-gray-400" id="status-text">Click Test to check</span>
                    </div>
                    <div id="status-details" class="hidden space-y-2 text-xs text-gray-500">
                        <div class="flex justify-between"><span>URL</span><span id="sd-url" class="text-gray-300 max-w-[140px] truncate">—</span></div>
                        <div class="flex justify-between"><span>Response</span><span id="sd-code" class="text-gray-300">—</span></div>
                        <div class="flex justify-between"><span>Latency</span><span id="sd-latency" class="text-gray-300">—</span></div>
                    </div>
                </div>
            </div>

            <!-- How to get token -->
            <div class="glass-card rounded-2xl border border-gray-800 p-5">
                <h3 class="font-bold text-white mb-3 flex items-center gap-2 text-sm">
                    <i class="fa-solid fa-circle-info text-yellow-400"></i> How to get LAT Token
                </h3>
                <ol class="text-xs text-gray-500 space-y-2 list-decimal list-inside">
                    <li>Open your Home Assistant</li>
                    <li>Go to your <strong class="text-gray-400">Profile</strong></li>
                    <li>Scroll to <strong class="text-gray-400">Long-Lived Access Tokens</strong></li>
                    <li>Click <strong class="text-gray-400">Create Token</strong></li>
                    <li>Give it a name like "manoranjan.dev"</li>
                    <li>Copy the token and paste it above</li>
                </ol>
            </div>

            <!-- Current config file status -->
            <div class="glass-card rounded-2xl border border-gray-800 p-5">
                <h3 class="font-bold text-white mb-3 flex items-center gap-2 text-sm">
                    <i class="fa-solid fa-file-code text-green-400"></i> Config File
                </h3>
                <div class="text-xs space-y-2">
                    <?php $configExists = file_exists('../includes/iot_config.php'); ?>
                    <div class="flex items-center gap-2">
                        <i class="fa-solid <?php echo $configExists ? 'fa-circle-check text-green-400' : 'fa-circle-xmark text-red-400'; ?>"></i>
                        <span class="text-gray-400">includes/iot_config.php <?php echo $configExists ? 'exists' : 'missing!'; ?></span>
                    </div>
                    <?php if ($configExists): ?>
                    <div class="flex items-center gap-2">
                        <i class="fa-solid <?php echo is_writable('../includes/iot_config.php') ? 'fa-circle-check text-green-400' : 'fa-triangle-exclamation text-yellow-400'; ?>"></i>
                        <span class="text-gray-400"><?php echo is_writable('../includes/iot_config.php') ? 'Writable (auto-update OK)' : 'Read-only (manual update needed)'; ?></span>
                    </div>
                    <?php endif; ?>
                </div>
            </div>

        </div>
    </div>

<script>
    // ---- Admin Pattern Canvas — DPR-aware, same logic as hacontrol.php ----
    (function() {
        const canvas  = document.getElementById('pattern-canvas');
        if (!canvas) return;
        const input   = document.getElementById('pattern-input');
        const seqDisp = document.getElementById('pattern-seq-display');

        let dots = [], selected = [], drawing = false, cursor = null, size = 0;

        function init() {
            const dpr = window.devicePixelRatio || 1;
            size = canvas.offsetWidth;                  // CSS px size (200)
            canvas.width  = size * dpr;
            canvas.height = size * dpr;
            const ctx = canvas.getContext('2d');
            ctx.setTransform(1,0,0,1,0,0);
            ctx.scale(dpr, dpr);
            dots = [];
            const pad = size * 0.17, gap = (size - 2 * pad) / 2;
            for (let r = 0; r < 3; r++)
                for (let c = 0; c < 3; c++)
                    dots.push({ x: pad + c * gap, y: pad + r * gap, id: r * 3 + c + 1, active: false });
            render();
        }

        function getPos(e) {
            const rect = canvas.getBoundingClientRect();
            const t = e.touches ? e.touches[0] : e;
            return {
                x: (t.clientX - rect.left) * (size / rect.width),
                y: (t.clientY - rect.top)  * (size / rect.height)
            };
        }

        function near(pos) {
            return dots.find(d => Math.hypot(d.x - pos.x, d.y - pos.y) < size * 0.11);
        }

        function render(flash) {
            const ctx = canvas.getContext('2d');
            ctx.clearRect(0, 0, size, size);
            const col = flash === 'error'
                ? { line:'#ef4444', dot:'#ef4444', glow:'rgba(239,68,68,0.25)' }
                : { line:'#a855f7', dot:'#a855f7', glow:'rgba(168,85,247,0.2)' };

            // Connection lines
            if (selected.length > 1) {
                ctx.beginPath();
                selected.forEach((id, i) => {
                    const d = dots.find(x => x.id === id);
                    i === 0 ? ctx.moveTo(d.x, d.y) : ctx.lineTo(d.x, d.y);
                });
                ctx.strokeStyle = col.line + '99'; ctx.lineWidth = 2.5;
                ctx.lineCap = 'round'; ctx.lineJoin = 'round'; ctx.stroke();
            }
            // Trailing line
            if (drawing && cursor && selected.length) {
                const last = dots.find(d => d.id === selected[selected.length - 1]);
                ctx.beginPath(); ctx.moveTo(last.x, last.y); ctx.lineTo(cursor.x, cursor.y);
                ctx.strokeStyle = col.line + '44'; ctx.lineWidth = 2; ctx.stroke();
            }
            // Dots
            const dotR = size * 0.055;
            dots.forEach(d => {
                if (d.active) {
                    ctx.beginPath(); ctx.arc(d.x, d.y, dotR * 2, 0, Math.PI*2);
                    ctx.fillStyle = col.glow; ctx.fill();
                    ctx.beginPath(); ctx.arc(d.x, d.y, dotR * 1.3, 0, Math.PI*2);
                    ctx.strokeStyle = col.dot; ctx.lineWidth = 2; ctx.stroke();
                } else {
                    ctx.beginPath(); ctx.arc(d.x, d.y, dotR * 1.3, 0, Math.PI*2);
                    ctx.strokeStyle = 'rgba(255,255,255,0.12)'; ctx.lineWidth = 1.5; ctx.stroke();
                }
                ctx.beginPath(); ctx.arc(d.x, d.y, dotR * 0.4, 0, Math.PI*2);
                ctx.fillStyle = d.active ? col.dot : 'rgba(255,255,255,0.4)'; ctx.fill();
                // Dot number (always visible)
                ctx.font = `bold ${size * 0.04}px monospace`;
                ctx.fillStyle = d.active ? '#ffffff' : 'rgba(255,255,255,0.2)';
                ctx.textAlign = 'center'; ctx.textBaseline = 'middle';
                ctx.fillText(d.id, d.x, d.y + dotR * 2.3);
            });
        }

        function updateDisplay() {
            const seq = selected.join('');
            if (seqDisp) seqDisp.textContent = seq ? seq.split('').join(' - ') : '—';
            if (input) input.value = seq;
        }

        const onStart = e => {
            e.preventDefault();
            drawing = true; selected = [];
            dots.forEach(d => d.active = false);
            const pos = getPos(e);
            const d = near(pos);
            if (d) { d.active = true; selected.push(d.id); }
            cursor = pos; render(); updateDisplay();
        };
        const onMove = e => {
            if (!drawing) return; e.preventDefault();
            cursor = getPos(e);
            const d = near(cursor);
            if (d && !d.active) { d.active = true; selected.push(d.id); }
            render(); updateDisplay();
        };
        const onEnd = e => {
            if (!drawing) return;
            drawing = false; cursor = null; render(); updateDisplay();
            if (selected.length > 0 && selected.length < 4) {
                if (seqDisp) seqDisp.style.color = '#f59e0b';
                setTimeout(() => { if(seqDisp) seqDisp.style.color = ''; }, 1500);
            }
        };

        canvas.addEventListener('mousedown',  onStart);
        canvas.addEventListener('mousemove',  onMove);
        window.addEventListener('mouseup',    onEnd);
        canvas.addEventListener('touchstart', onStart, { passive: false });
        canvas.addEventListener('touchmove',  onMove,  { passive: false });
        canvas.addEventListener('touchend',   onEnd,   { passive: false });

        window.addEventListener('resize', init);
        init();

        window.adminPatternClear = function() {
            selected = []; dots.forEach(d => d.active = false);
            drawing = false; cursor = null;
            if (input) input.value = '';
            if (seqDisp) seqDisp.textContent = '—';
            render();
        };
    })();

    function toggleToken() {
        const el = document.getElementById('ha_token');
        const eye = document.getElementById('token-eye');
        if (el.type === 'password') {
            el.type = 'text';
            eye.className = 'fa-solid fa-eye-slash text-sm';
        } else {
            el.type = 'password';
            eye.className = 'fa-solid fa-eye text-sm';
        }
    }

    async function testConnection() {
        const url = document.getElementById('ha_url').value;
        const dot = document.getElementById('status-dot');
        const text = document.getElementById('status-text');
        const details = document.getElementById('status-details');
        const badge = document.getElementById('test-badge');

        dot.className = 'w-2 h-2 rounded-full bg-yellow-400 animate-ping';
        text.textContent = 'Testing connection...';
        details.classList.add('hidden');

        const start = Date.now();
        try {
            const res = await fetch('../api/ha_proxy.php?entity=sensor.time&_test=1&_t=' + Date.now());
            const latency = Date.now() - start;
            const data = await res.json();

            if (!data.error) {
                dot.className = 'w-2 h-2 rounded-full bg-green-400';
                text.textContent = '✓ Connected to Home Assistant!';
                text.className = 'text-green-400';
                badge.textContent = 'ONLINE';
                badge.className = 'flex px-3 py-1 rounded-full text-xs font-bold bg-green-500/10 text-green-400 border border-green-500/20';
            } else {
                throw new Error(data.error);
            }

            details.classList.remove('hidden');
            document.getElementById('sd-url').textContent = url;
            document.getElementById('sd-code').textContent = res.status;
            document.getElementById('sd-latency').textContent = latency + 'ms';
        } catch(e) {
            dot.className = 'w-2 h-2 rounded-full bg-red-400';
            text.textContent = '✗ Connection failed: ' + e.message;
            text.className = 'text-red-400';
            badge.textContent = 'OFFLINE';
            badge.className = 'flex px-3 py-1 rounded-full text-xs font-bold bg-red-500/10 text-red-400 border border-red-500/20';
        }
        badge.classList.remove('hidden');
    }
</script>

<?php include 'includes/admin_footer.php'; ?>
